### ISSUE TITLE
Error: Cannot find module 'sequelize'

### ISSUE THREAD

**Issue by morenoh149** [zekenie/sequelize-erd#1]
I installed the package and added it to my package.json scripts.

running returns
```
$ npm run erd

> foo@0.0.1 erd /Users/harrymoreno/programming/foo
> sequelize-erd --source ./src/node_modules/lib/database.js --destination ./erd.svg

module.js:442
    throw err;
    ^

Error: Cannot find module 'sequelize'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/harrymoreno/programming/foo/src/node_modules/lib/database.js:1:79)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "erd"
npm ERR! node v6.2.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! effigy@0.0.1 erd: `sequelize-erd --source ./src/node_modules/lib/database.js --destination ./erd.svg`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the effigy@0.0.1 erd script 'sequelize-erd --source ./src/node_modules/lib/database.js --destination ./erd.svg'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the effigy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sequelize-erd --source ./src/node_modules/lib/database.js --destination ./erd.svg
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs effigy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls effigy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/harrymoreno/programming/foo/npm-debug.log
```
thoughts?

**Comment by sohini-roy** [comment]
"npm install --save sequelize" solved this for me. Good luck :+1:

**Comment by zekenie** [comment]
Hey, @morenoh149 sorry it took me over a year to see this. I didn't realize people were using this. If you still are trying to use this, or wouldn't mind helping me make this better, can you send me the package json of the project you're trying to use this with?

**Comment by morenoh149** [comment]
nope sorry, I was trying to build a visualization for some models I autogenerated against a new database. But later found that dbeaver is better suited for that task.
