### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by NFhbar** [zekenie/sequelize-erd#10]
I get the following error when running:
```
$ npm run erd
/Users/n/Desktop/repos/api/node_modules/sequelize-erd/index.js:40
        ? Object.values(model.attributes)
                 ^

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at modelTemplate (/Users/nico/Desktop/repos/charge-api/node_modules/sequelize-erd/index.js:40:18)
    at modelsArr.filter.map.model (/Users/nico/Desktop/repos/charge-api/node_modules/sequelize-erd/index.js:137:21)
    at Array.map (<anonymous>)
    at generateDot (/Users/nico/Desktop/repos/charge-api/node_modules/sequelize-erd/index.js:137:8)
    at module.exports (/Users/nico/Desktop/repos/charge-api/node_modules/sequelize-erd/index.js:165:15)
    at Object.<anonymous> (/Users/nico/Desktop/repos/charge-api/node_modules/sequelize-erd/bin/generate:21:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```

`package.json`:
```
"erd": "sequelize-erd --source ./tasks/generateERD/index.js --destination ./erd.svg"
```

`tasks/generateERD/index.js`:
```
const { sequelize } = require('../../models/index.js')

// Require our models. Running each module registers the model into sequelize
// so any other part of the application can simply call sequelize.model('User')
// to get access to the User model.
require('../../models')

module.exports = sequelize
```

`models/index.js`:
```
'use strict'

const fs = require('fs')
const path = require('path')
const Sequelize = require('sequelize')
const basename = path.basename(__filename)
const env = process.env.NODE_ENV || 'development'
const config = require(path.join(__dirname, '/../config/config.js'))[env]
const db = {}

let sequelize
if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable], config)
} else {
  sequelize = new Sequelize(
    config.database,
    config.username,
    config.password,
    config
  )
}

fs.readdirSync(__dirname)
  .filter(file => {
    return (
      file.indexOf('.') !== 0 && file !== basename && file.slice(-3) === '.js'
    )
  })
  .forEach(file => {
    const model = sequelize['import'](path.join(__dirname, file))
    db[model.name] = model
  })

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db)
  }
})

// sequelize.sync()

db.sequelize = sequelize
db.Sequelize = Sequelize

module.exports = { db, sequelize, Sequelize }
```

**Comment by marcobiedermann** [comment]
@NFhbar 

Which version of `Sequelize` are you using?
Same happens for me with V5.
I guess this issue is caused by a compatibility issue with the latest version.

**Comment by NFhbar** [comment]
@marcobiedermann yeah, I am on ` "sequelize": "^5.8.7"`

**Comment by marcobiedermann** [comment]
@nfhbar

In the meantime I figured out that this has already been solved in https://github.com/zekenie/sequelize-erd/commit/ac60610c4bb4f1c9b7e0a1739c5468bafc34cb95 but the latest changes are not published to npm.
Therefore you have to install this package from GitHub via `npm install zekenie/sequelize-erd`

**Comment by marcobiedermann** [comment]
@NFhbar 

I think this issue is caused due to the changed model definition in V5.
I’m using

```js
class MyModel {}

MyModel.init({})

module.export = MyModel;
```

and it works fine for me.

**Comment by NFhbar** [comment]
I see, also working with ` npm install zekenie/sequelize-erd`.

**Comment by samypr100** [comment]
You can just change it to `model.rawAttributes` instead of `model.attributes` and it should just work ™️  on the latest **sequelize**.

**Comment by Bahramibh** [comment]
yes , we should use **model.rawAttributes , instead of model.attributes** 
where we have bulk upsert or something like this
